travis: Set up Mac builds

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -8,6 +8,7 @@ node_js:
 
 os:
   - linux
+  - osx
 
 addons:
   apt:
@@ -38,13 +39,23 @@ test:
   - echo "Tests not set up yet"
 
 before_deploy:
-  - mv dist/*.AppImage dist/electest-$TRAVIS_TAG-$(uname -m).AppImage
-
+  - |
+    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
+      export RELEASE_FILE="dist/electest-$TRAVIS_TAG-$(uname -m).AppImage"
+      mv dist/*.AppImage "$RELEASE_FILE"
+    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
+      export RELEASE_FILE="dist/electest-$TRAVIS_TAG.dmg"
+      mv dist/mac/*.dmg "$RELEASE_FILE"
+    else
+      echo "Can't find release image for $TRAVIS_OS_NAME" 2>&1
+      exit 1
+    fi
 deploy:
   provider: releases
   api_key:
     secure: Jrbjk+hDh4pcLiHQ6+CYvickZbpL4+lS5GZOzrnImzKm7ksantQg9wtu4mWGpPG1Kjbk3/qbsCsTcZBi3BW9KAvGDj94Q+x3kFrOuIbQvmemIzWQ8IsNPBkQYv5uxvNmG9U+2ayhg+Dv0gLk7552G4Tl1RPVUXm8RWEBgrU6+BnWtbZwtTuroQEHemxaIBnZWjDapZEcFSow/40ZjyqEFdFfC0bljtds37UpMQZUtZXZqR2RZmp5WTzoroiN+wkmhxsn5UQhBRieEb3kst23pBh6tsJ+00WG7MssTWZsE4vXLaGqFLzBzufFlzFU4tOWxcwm0g+farJHc7J4yYzTWJRjNRq3Vjmq7NGyLAGlin/QMqXmzBc1yCoxms6DlHdH/Jn1xNqc2x9VbS5oCOrautTg2r5Sk89yVX2Qn6Rensb+wsNkmfRMZiIdE0Rglc67Qr3oJaO7ZWiendI4SSj+pesSb9zhqZ8adqpOHgK0D/Ta4ot1pZWOdBgP98KglrLex55EW0AIzFs+ADqcj5w0n4FVpFw71vQ8xqZ3ehurUXnGB3Lk1B8A/FdjlOgtnoHqQ+YCJii9QcuIIwTv14I06VOWX4D6s08LIDzWvXczglAnvcMlgCq/6hSBzmnK4NMm8Vs0koUmwMGvmScnFNPX6YURIn69nCeBTIe1Dqggink=
-  file: "dist/electest-$TRAVIS_TAG-$(uname -m).AppImage"
+  file_glob: true
+  file: "${RELEASE_FILE}"
   skip_cleanup: true
   on:
     repo: emk/electron-test
